services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fpa-api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: fpa-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fpa-celery-worker
    command: celery -A app.tasks.celery_app.celery worker --loglevel=info
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - api
      - redis
      - db

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fpa-celery-beat
    command: celery -A app.tasks.celery_app.celery beat --loglevel=info
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - api
      - redis
      - db

  redis:
    image: redis:7
    container_name: fpa-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: fpa-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - fpa-db-data:/var/lib/postgresql/data

  spark-master:
    image: bitnami/spark:3.5
    container_name: fpa-spark-master
    profiles:
      - analytics
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8081:8080"

  spark-worker:
    image: bitnami/spark:3.5
    container_name: fpa-spark-worker
    profiles:
      - analytics
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    depends_on:
      - spark-master

volumes:
  fpa-db-data:
